spring:
  # H2 Console Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  # Datasource Settings
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true