export const ITEM_LIST_TITLE = "상품 목록";
export const SUMMARY_TITLE = "Summary";
export const TOTAL_PRICE = "총금액";
export const ADD_ITEM = "추가";
export const EMAIL = "이메일";
export const ADDRESS = "주소";
export const ZIP_CODE = "우편번호";
export const NOTE_MESSAGE = "당일 오후 2시 이후의 주문은 다음날 배송을 시작합니다."
export const PAYMENT = "결제하기";
export const WON = "원";
export const UNIT = "개";
export const INVALID_EMAIL = "올바른 이메일 형식이 아닙니다.";
export const INVALID_ZIP_CODE = "올바른 우편번호 형식이 아닙니다.";
export const QUANTITY_PLUS = "+";
export const QUANTITY_MINUS = "-";
export const EMAIL_TAG = "email";
export const ADDRESS_TAG = "address";
export const ZIP_CODE_TAG = "zipCode";